#pragma once

enum EntityType
{
    ENTITY_NONE,
	ENTITY_PLAYER,
    ENTITY_TROOP,
    ENTITY_BARBARE,
    ENTITY_ARCHER,

    ENTITY_BUILDING,
    ENTITY_FARM,
    ENTITY_TAVERN,
    ENTITY_TRAP,
    ENTITY_TOUR,

    ENTITY_REMOVABLE,
    ENTITY_GRASS,
    ENTITY_ROCK,
    ENTITY_TREE,
    ENTITY_PATH,
};